#!/usr/bin/env python3
"""
规则打包工具
将多个 YARA 规则打包成单个文件
"""

import os
import sys
import argparse
from pathlib import Path
from typing import List


class RulePacker:
    """规则打包器"""
    
    def __init__(self):
        self.rules_content = []
        self.rules_count = 0
    
    def add_rule_file(self, file_path: Path) -> bool:
        """
        添加规则文件
        
        Args:
            file_path: 规则文件路径
            
        Returns:
            是否添加成功
        """
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            self.rules_content.append(f"// Rule from: {file_path.name}\n{content}\n")
            self.rules_count += 1
            print(f"✅ 添加规则: {file_path.name}")
            return True
            
        except Exception as e:
            print(f"❌ 读取失败 [{file_path.name}]: {e}")
            return False
    
    def scan_directory(self, directory: Path, recursive: bool = True):
        """
        扫描目录中的规则文件
        
        Args:
            directory: 规则目录
            recursive: 是否递归
        """
        pattern = '**/*.yar*' if recursive else '*.yar*'
        rule_files = list(directory.glob(pattern))
        
        print(f"\n📂 扫描目录: {directory}")
        print(f"📄 找到 {len(rule_files)} 个规则文件\n")
        
        for file_path in rule_files:
            self.add_rule_file(file_path)
    
    def pack(self, output_path: Path, include_header: bool = True):
        """
        打包规则到文件
        
        Args:
            output_path: 输出文件路径
            include_header: 是否包含文件头
        """
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                if include_header:
                    f.write("/*\n")
                    f.write(" * YARA Rules Collection\n")
                    f.write(f" * Total Rules: {self.rules_count}\n")
                    f.write(" * Generated by YARA-X Manager\n")
                    f.write(" */\n\n")
                
                f.write("\n".join(self.rules_content))
            
            print(f"\n✅ 打包完成!")
            print(f"📦 输出文件: {output_path}")
            print(f"📊 规则数量: {self.rules_count}")
            print(f"💾 文件大小: {output_path.stat().st_size / 1024:.2f} KB")
            
        except Exception as e:
            print(f"❌ 打包失败: {e}")
            sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description='规则打包工具 - 合并多个 YARA 规则文件'
    )
    parser.add_argument(
        '-i', '--input',
        type=str,
        required=True,
        help='输入目录或文件'
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        required=True,
        help='输出文件路径'
    )
    parser.add_argument(
        '-r', '--recursive',
        action='store_true',
        help='递归扫描子目录'
    )
    parser.add_argument(
        '--no-header',
        action='store_true',
        help='不包含文件头'
    )
    
    args = parser.parse_args()
    
    # 验证输入路径
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"❌ 错误: 路径不存在 [{input_path}]")
        sys.exit(1)
    
    # 创建打包器
    packer = RulePacker()
    
    # 添加规则
    if input_path.is_file():
        packer.add_rule_file(input_path)
    else:
        packer.scan_directory(input_path, args.recursive)
    
    # 打包
    output_path = Path(args.output)
    packer.pack(output_path, not args.no_header)


if __name__ == '__main__':
    main()
